### ISSUE TITLE
catkin_make fails

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [ipa320/bride#102]
[Ubuntu 13.10, ROS Hydro Desktop Full from Source]

Hi,
  I tried installing from source using the instructions published on the repository's main page (README.md), but _catkin_make_ failed due to dependency problems listed below.
  I have ROS Hydro installed from source, and had Eclipse LUNA installed in /opt/eclipse.  After the first failed attempt at building BRIDE, I removed my eclipse install and tried again but got the same result.

  Any assistance would be welcome.

Cheers,
Nap

**Problem #1:**
Cannot complete the install because of a conflicting dependency.
 Software being installed: Core Resource Management 3.9.1.v20140825-1431 (org.eclipse.core.resources 3.9.1.v20140825-1431)
 Software currently installed: Eclipse Modeling Tools 4.4.0.20140612-0500 (epp.package.modeling 4.4.0.20140612-0500)
 Only one of the following can be installed at once: 
  Core Resource Management 3.9.1.v20140825-1431 (org.eclipse.core.resources 3.9.1.v20140825-1431)
  Core Resource Management 3.9.0.v20140514-1307 (org.eclipse.core.resources 3.9.0.v20140514-1307)
 Cannot satisfy dependency:
  From: Eclipse Modeling Tools 4.4.0.20140612-0500 (epp.package.modeling 4.4.0.20140612-0500)
  To: org.eclipse.epp.package.modeling.feature.feature.group [4.4.0.20140612-0500]
 Cannot satisfy dependency:
  From: EPP Modeling Feature 4.4.0.20140612-0500 (org.eclipse.epp.package.modeling.feature.feature.group 4.4.0.20140612-0500)
  To: org.eclipse.platform.feature.group [4.4.0.v20140606-1558]
 Cannot satisfy dependency:
  From: Eclipse Platform 4.4.0.v20140606-1558 (org.eclipse.platform.feature.group 4.4.0.v20140606-1558)
  To: org.eclipse.core.resources [3.9.0.v20140514-1307]

**Problem #2:**
Cannot complete the install because one or more required items could not be found.
 Software being installed: Bcmx Plugin 1.0.0.201302261222 (org.best_of_robotics.model.bcmx.diagram 1.0.0.201302261222)
 Missing requirement: Bcmx Plugin 1.0.0.201302261222 (org.best_of_robotics.model.bcmx.diagram 1.0.0.201302261222) requires 'bundle org.eclipse.gmf.tooling.runtime 0.0.0' but it could not be found

**Problem #3:** (Presumably because the build failed)
The installable unit org.best_of_robotics.transform.service.access has not been found.
Application failed, log file location: /home/user/src/bride_ws/src/bride/bride/eclipse/configuration/1418848900656.log

**Comment by abubeck** [comment]
Hi, thanks for reporting. The eclipse release specified in the installer was not in sync with the eclipse repo's in the development branch. I updated everything and tested on ubuntu 12.04 and 14.04. 
Please update your clone and try again. If you still have problems feel free to reopen this issue.

PS: the bride installation does not interfere with your other eclipse installations
