### ISSUE TITLE
Problem with bride tutorial

### ISSUE THREAD

**Issue by ghost** [ipa320/bride#106]
Hello! I try to follow [this](http://wiki.ros.org/bride/Tutorials/Creating-nodes-with-BRIDE-and-cplusplus) tutorial but when i click on the images the [link](http://cybernotic.org/bride/img/ROSWizard.png) doesn't work. I need this images to complete the tutorial, anyone can help me? Many thank!

**Comment by fmessmer** [comment]
bride is neither actively developed nor maintained any longer..sorry
@ipa-fez @ipa-jba close?
