### ISSUE TITLE
default.ros_package created if clicking on finish too early

### ISSUE THREAD

**Issue by ugocupcic** [ipa320/bride#13]
When creating a ROS Package diagram, Finish can be clicked even without modifying the file name. If you modify the first one (default.ros_package_diagram -> some_pkg.ros_package_diagram), then click finish, the second file generated (default.ros_package) keeps the name default.ros_package instead of having the same name as the .ros_package_diagram. This makes it impossible to compile without renaming the file by hand.

**Comment by abubeck** [comment]
Thanks a lot for reporting. The finish button is now shown only after accepting the model filename. 
Will be included in next release.
