### ISSUE TITLE
ask user before overwriting files

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/bride#32]
e.g. package.xml and CMakelists (file which have no protected regions) but also cpp and py files
let the user decide which parts should be overwritten e.g. by using meld (or similar tool)

This caused me troubles:
-  when generating python and cpp code from the same model.
- when adding a second author or maintainer

**Comment by abubeck** [comment]
When generating python check if cpp was generated before and vice versa. If true inform the user about possible overwrites.
