### ISSUE TITLE
Produce Error during generation if no message type is set

### ISSUE THREAD

**Issue by ipa-fmw-ms** [ipa320/bride#41]
If there is no Msg set in bride, it is still possible to Generate code, which cannot build.

**Comment by floweisshardt** [comment]
make complains about an include for an header file '.h' due to wrong substitution

**Comment by abubeck** [comment]
That was already catched by the model validation. Therefore you should have had a validation error for the model. I additionally now check for errors in the generation to make it only possible to generate code when the model is valid.
Does this fix the issue?

**Comment by floweisshardt** [comment]
@ipa-fmw-ms can you please test again and check if it is fixed?

**Comment by ipa-fmw-ms** [comment]
Now I get two Errors in the Problem Tab.
But the Code still gets generated with empty #include <.h>
