### ISSUE TITLE
error with ROSPackageWizard

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/bride#51]
I failed creating a package because I used the default location "~/catkin_ws/src" for creating a new package "my_test_package".
Correct would be to "mkdir ~/catkin_ws/test" and then run the wizard and select "~/catkin_ws/src/my_test_package" as location.

this is not very intuitive for the user, especially not when the default location can **never** be uses this way.

Suggestions:
- do not let the user create a package through the wizzard if the package name is not the same as the location directory
- elimintate the "use default location" checkbox

or
- create the directory with the package name automatically in the background

**Comment by abubeck** [comment]
A bug in creating packages in the default location is fixed no (see #66 ).
Additional I created a validation routine that checks if the location name is equal to the project name.
