### ISSUE TITLE
create documentation (diagramm) for simplified BRIDE node model

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/bride#52]
explain internal coordination model in a diagramm:
configure - trigger - read inputs - update - send outputs - trigger - ...

should list the following possibilities:
- trigger update by fix loop_rate
- trigger by callbacks
- mixed version

**Comment by abubeck** [comment]
Created https://github.com/ipa320/bride/wiki/Internal-node-behaviour to describe node behavior.
