### ISSUE TITLE
catkin_lint reports errors on freshly generated package

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/bride#85]
error: build include path 'common/include' does not exist
error: catkin_package() exports package include path that is not installed

**Comment by floweisshardt** [comment]
removing the include path probably leads to a new error after code generation. Will the include path be inserted again during generation?
Otherwise we could just create the folder and keep the CMakeLists.txt as it is.

**Comment by abubeck** [comment]
Since no files are generated into a "common/include"-folder based on the code generation, it makes no sense to create one or add one in the CMakeLists.txt.

**Comment by floweisshardt** [comment]
ok, sorry. I thought it would.
