### ISSUE TITLE
capability editor: add property to fill limits for parameters

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/bride#94]
in BRIDE 0.3.3 it is only possible to specify the default value, but the range limits e.g. for a parameter of type int is fixed to -100 to +100.
`gen.add("timeout", int_t, 0, "Autogenerated parameter based on model.", , -100, 100)`

Should be handled for all type of parameters (int, double, string, int, bool, XmlRpcValue).

**Comment by abubeck** [comment]
Duplicate of #92 .
