### ISSUE TITLE
CMakeLists.txt and package.xml generation incomplete/inconsistent, catkin_lint errors

### ISSUE THREAD

**Issue by ipa-fmw-ms** [ipa320/bride#99]
catkin_lint output:
1: build include path 'common/include' does not exist
2: catkin_package() exports package include path that is not installed
3: unconfigured build_depend on 'actionlib'

Also, the Intendation of dynamic_reconfigure is wrong

reproduce: catkin_lint cob_teleop_cob4

**Comment by abubeck** [comment]
catkin_lint doen't report any error, now. (only one warning regarding naming)
